# Generated by Django 6.1 on 2026-08-23 02:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_posts', to='common.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DutyTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reported', 'Reported')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_tours_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_duty', 'On duty'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='on_duty', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to='common.person')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='duty.dutypost')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='duty.dutytour')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SoldierPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soldier_postings_accepted', to=settings.AUTH_USER_MODEL)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_postings', to='common.organization')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soldier_postings_made', to=settings.AUTH_USER_MODEL)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='common.person')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_postings', to='common.organization')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dutytour',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_duty_tour_number'),
        ),
        migrations.AddConstraint(
            model_name='dutyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['on_duty', 'completed'])), fields=('tour', 'soldier'), name='unique_soldier_per_open_tour'),
        ),
    ]
