# Generated by Django 6.1 on 2026-08-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0006_unique_open_duty_tour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadeAbsenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('document', models.FileField(upload_to='parade_state/absence/')),
                ('document_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parade_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_documents', to='duty.paradestate')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parade_absence_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-document_date', '-uploaded_at', '-pk'],
            },
        ),
    ]
