# Generated by Django 6.1 on 2026-08-23 02:19

from django.db import migrations, models

from common.compat import make_check_constraint


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_drop_person_on_leave_column'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointmenthistory',
            constraint=make_check_constraint(models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), 'appointment_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='civileducation',
            constraint=make_check_constraint(models.Q(('to_date__isnull', True), ('to_date__gt', models.F('from_date')), _connector='OR'), 'civil_education_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='medicalcategory',
            constraint=make_check_constraint(models.Q(('to_date__isnull', True), ('to_date__gt', models.F('from_date')), _connector='OR'), 'medical_category_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='servicehistory',
            constraint=make_check_constraint(models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), 'service_history_valid_dates'),
        ),
    ]
