# Generated by Django 6.1 on 2026-08-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_drop_person_on_leave_column'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='appointment_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='civileducation',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__isnull', True), ('to_date__gt', models.F('from_date')), _connector='OR'), name='civil_education_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='medicalcategory',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__isnull', True), ('to_date__gt', models.F('from_date')), _connector='OR'), name='medical_category_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='servicehistory',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='service_history_valid_dates'),
        ),
    ]
