# Generated by Django 6.1 on 2026-08-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_person_all_apr_person_army_courses_person_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='army_courses',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cadres',
        ),
        migrations.RemoveField(
            model_name='person',
            name='civil_education',
        ),
        migrations.RemoveField(
            model_name='person',
            name='physical_efficiency',
        ),
        migrations.RemoveField(
            model_name='person',
            name='specialist_cadre',
        ),
    ]
