# Generated by Django 6.1 on 2026-08-26 12:07

from django.db import migrations


def copy_mobile_numbers(apps, schema_editor):
    Person = apps.get_model('common', 'Person')
    MobileNumber = apps.get_model('common', 'MobileNumber')
    for person in Person.objects.all().iterator():
        values = (
            ('personal', person.mobile_number_1),
            ('personal', person.mobile_number_2),
            ('nok', person.nok_mobile_number),
        )
        for number_type, number in values:
            number = (number or '').strip()
            if number:
                MobileNumber.objects.get_or_create(
                    person_id=person.pk,
                    type_of_number=number_type,
                    mobile_number=number,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_person_all_apr'),
    ]

    operations = [
        migrations.RunPython(copy_mobile_numbers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='person',
            name='mobile_number_1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mobile_number_2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nok_mobile_number',
        ),
    ]
