# Generated by Django 6.1 on 2026-08-26 12:18

from django.db import migrations


def copy_appointments(apps, schema_editor):
    Person = apps.get_model('common', 'Person')
    AppointmentHistory = apps.get_model('common', 'AppointmentHistory')
    for person in Person.objects.all().iterator():
        start_date = person.present_rank_date or person.doe
        for appointment_name in (
            person.present_appointment,
            person.previous_appointment,
        ):
            appointment_name = (appointment_name or '').strip()
            if appointment_name:
                AppointmentHistory.objects.get_or_create(
                    person_id=person.pk,
                    organization_id=person.organization_id,
                    appointment_name=appointment_name,
                    start_date=start_date,
                    end_date=None,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_person_mobile_number_1_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_appointments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='person',
            name='present_appointment',
        ),
        migrations.RemoveField(
            model_name='person',
            name='previous_appointment',
        ),
    ]
