# Generated by Django 6.1 on 2026-08-26 12:21

from django.db import migrations


def copy_previous_units(apps, schema_editor):
    Person = apps.get_model('common', 'Person')
    AppointmentHistory = apps.get_model('common', 'AppointmentHistory')
    for person in Person.objects.all().iterator():
        value = (person.previous_unit_organizations or '').strip()
        if value:
            AppointmentHistory.objects.get_or_create(
                person_id=person.pk,
                organization_id=person.organization_id,
                appointment_name=f"Previous unit/organization: {value}",
                start_date=person.doe,
                end_date=None,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_person_present_appointment_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_previous_units, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='person',
            name='previous_unit_organizations',
        ),
    ]
