# Generated by Django 6.1 on 2026-08-26 12:27

import django.db.models.deletion
from django.db import migrations, models


def copy_family_details(apps, schema_editor):
    Person = apps.get_model('common', 'Person')
    Family = apps.get_model('common', 'Family')
    for person in Person.objects.all().iterator():
        parents = (person.parents_details or '').strip()
        spouse_children = (person.spouse_children_details or '').strip()
        if parents:
            Family.objects.create(
                person_id=person.pk,
                relation_name='Parents',
                remarks=parents,
            )
        if spouse_children:
            Family.objects.create(
                person_id=person.pk,
                relation_name='Spouse / Children',
                remarks=spouse_children,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_remove_person_previous_unit_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.CharField(max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='common.person')),
            ],
            options={
                'verbose_name': 'Family member',
                'verbose_name_plural': 'Family members',
                'ordering': ['relation_name', 'id'],
            },
        ),
        migrations.RunPython(copy_family_details, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='person',
            name='parents_details',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spouse_children_details',
        ),
    ]
