# Generated by Django 6.1 on 2026-08-26 14:04

from django.db import migrations


def copy_rank_dates(apps, schema_editor):
    Person = apps.get_model('common', 'Person')
    ServiceHistory = apps.get_model('common', 'ServiceHistory')
    for person in Person.objects.all().iterator():
        present_date = person.present_rank_date
        previous_date = person.previous_rank_date
        if present_date:
            ServiceHistory.objects.get_or_create(
                person_id=person.pk,
                rank_id=person.rank_id,
                organization_id=person.organization_id,
                start_date=present_date,
                defaults={"end_date": None},
            )
        if previous_date and previous_date != present_date:
            end_date = present_date if present_date and present_date > previous_date else None
            ServiceHistory.objects.get_or_create(
                person_id=person.pk,
                rank_id=person.rank_id,
                organization_id=person.organization_id,
                start_date=previous_date,
                defaults={"end_date": end_date},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_person_parents_details_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_rank_dates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='person',
            name='present_rank_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='previous_rank_date',
        ),
    ]
