# Generated by Django 6.1 on 2026-08-26 14:39

from django.db import migrations, models


def classify_existing_ranks(apps, schema_editor):
    Rank = apps.get_model('common', 'Rank')
    officer_terms = (
        '2lt', 'second lieutenant', 'lt', 'lieutenant', 'capt', 'captain',
        'maj', 'major', 'lt col', 'lieutenant colonel', 'col', 'colonel',
        'brig', 'general',
    )
    jco_terms = ('wo', 'warrant officer', 'swo', 'mwo', 'master warrant')
    for rank in Rank.objects.all():
        name = ' '.join(rank.rank_name.lower().replace('.', '').split())
        category = 'or'
        if any(name == term or name.startswith(term + ' ') for term in jco_terms):
            category = 'jco'
        elif any(name == term or name.startswith(term + ' ') for term in officer_terms):
            category = 'officer'
        rank.category = category
        rank.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_person_present_rank_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='category',
            field=models.CharField(choices=[('officer', 'Officer'), ('jco', 'JCO'), ('or', 'OR')], default='or', max_length=20),
        ),
        migrations.RunPython(classify_existing_ranks, migrations.RunPython.noop),
    ]
