# Generated by Django 5.2.5 on 2026-09-14 11:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_ere_organizations(apps, schema_editor):
    Organization = apps.get_model("common", "Organization")
    EREOrganization = apps.get_model("common", "EREOrganization")
    for org in Organization.objects.filter(unit_kind="ere"):
        EREOrganization.objects.get_or_create(
            organization=org,
            defaults={"name": org.organization_name},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_organization_ere_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EREOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('organization', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ere_entry', to='common.organization')),
            ],
            options={
                'verbose_name': 'ERE organization',
                'verbose_name_plural': 'ERE organizations',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(backfill_ere_organizations, migrations.RunPython.noop),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_organization_ere_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EREOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('organization', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ere_entry', to='common.organization')),
            ],
            options={
                'verbose_name': 'ERE organization',
                'verbose_name_plural': 'ERE organizations',
                'ordering': ['name'],
            },
        ),
    ]
