# Generated by Django 6.1 on 2026-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_co_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dashboard/slides/')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dashboard slide',
                'verbose_name_plural': 'Dashboard slides',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HallOfFameCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rank', models.CharField(blank=True, max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dashboard/cos/')),
                ('tenure_start', models.DateField(blank=True, null=True)),
                ('tenure_end', models.DateField(blank=True, help_text='Leave blank if this officer is still serving.', null=True)),
                ('quote', models.TextField(blank=True)),
                ('citation', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False, help_text='Shown as the serving Commanding Officer on the dashboard.')),
                ('display_order', models.PositiveSmallIntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hall of Fame CO',
                'verbose_name_plural': 'Hall of Fame COs',
                'ordering': ['-is_current', 'display_order', '-tenure_start', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard/achievements/')),
                ('display_order', models.PositiveSmallIntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit achievement',
                'verbose_name_plural': 'Unit achievements',
                'ordering': ['display_order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='bi-award', help_text='Bootstrap icon class, for example bi-award or bi-shield-check.', max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit highlight',
                'verbose_name_plural': 'Unit highlights',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(default='1 Bangladesh Infantry Regiment', max_length=150)),
                ('short_name', models.CharField(default='1 BIR', max_length=40)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, default="Ramu Cantonment, Cox's Bazar", max_length=150)),
                ('raised_on', models.CharField(blank=True, max_length=80)),
                ('war_cry', models.CharField(blank=True, max_length=120)),
                ('about', models.TextField(blank=True)),
                ('crest', models.ImageField(blank=True, null=True, upload_to='dashboard/crest/')),
            ],
            options={
                'verbose_name': 'Unit profile',
                'verbose_name_plural': 'Unit profile',
            },
        ),
    ]
