from django.urls import path

from . import views

app_name = "training"

urlpatterns = [
    path(
        "training/",
        views.TrainingHomeView.as_view(),
        name="training_home",
    ),
    path(
        "training/soldier/<int:pk>/g-matters/",
        views.SoldierGMatterView.as_view(),
        name="soldier_g_matter",
    ),
    path(
        "training/yearly-plans/",
        views.YearlyPlanListView.as_view(),
        name="yearly_plan_list",
    ),
    path(
        "training/yearly-plans/<int:pk>/edit/",
        views.YearlyPlanUpdateView.as_view(),
        name="yearly_plan_edit",
    ),
    path(
        "training/major-commitments/",
        views.MajComListView.as_view(),
        name="majcom_list",
    ),
    path(
        "training/major-commitments/<int:pk>/edit/",
        views.MajComUpdateView.as_view(),
        name="majcom_edit",
    ),
    path(
        "training/sports/",
        views.SportsListView.as_view(),
        name="sports_list",
    ),
    path(
        "training/sports/<int:pk>/edit/",
        views.SportsUpdateView.as_view(),
        name="sports_edit",
    ),
    path(
        "training/leave/",
        views.LeaveListView.as_view(),
        name="leave_list",
    ),
    path(
        "training/leave/<int:pk>/",
        views.LeaveManageView.as_view(),
        name="leave_manage",
    ),
    path(
        "training/leave/request/<int:pk>/decide/",
        views.LeaveDecisionView.as_view(),
        name="leave_decide",
    ),
    path(
        "training/qualifications/",
        views.QualListView.as_view(),
        name="qual_list",
    ),
    path(
        "training/qualifications/<int:pk>/edit/",
        views.QualUpdateView.as_view(),
        name="qual_edit",
    ),
    path(
        "training/ipft/",
        views.IPFTListView.as_view(),
        name="ipft_list",
    ),
    path(
        "training/ipft/<int:pk>/edit/",
        views.IPFTUpdateView.as_view(),
        name="ipft_edit",
    ),
    path(
        "training/ret/",
        views.RETHomeView.as_view(),
        name="ret_list",
    ),
    path(
        "training/ret/gp-firing/",
        views.GPFiringListView.as_view(),
        name="gp_firing_list",
    ),
    path(
        "training/ret/gp-firing/<int:pk>/edit/",
        views.GPFiringUpdateView.as_view(),
        name="gp_firing_edit",
    ),
    path(
        "training/ret/sosn-firing/",
        views.SOSNFiringListView.as_view(),
        name="sosn_firing_list",
    ),
    path(
        "training/ret/sosn-firing/<int:pk>/edit/",
        views.SOSNFiringUpdateView.as_view(),
        name="sosn_firing_edit",
    ),
    path(
        "training/ret/cas-trophy/",
        views.CASTrophyListView.as_view(),
        name="cas_trophy_list",
    ),
    path(
        "training/ret/cas-trophy/<int:pk>/edit/",
        views.CASTrophyUpdateView.as_view(),
        name="cas_trophy_edit",
    ),
    path(
        "training/ret/grenade-firing/",
        views.GrenadeFiringListView.as_view(),
        name="grenade_firing_list",
    ),
    path(
        "training/ret/grenade-firing/<int:pk>/edit/",
        views.GrenadeFiringUpdateView.as_view(),
        name="grenade_firing_edit",
    ),
    path(
        "training/march-course/",
        views.MarchCourseHomeView.as_view(),
        name="march_course_list",
    ),
    path(
        "training/march-course/speed-march/",
        views.SpeedMarchListView.as_view(),
        name="speed_march_list",
    ),
    path(
        "training/march-course/speed-march/<int:pk>/edit/",
        views.SpeedMarchUpdateView.as_view(),
        name="speed_march_edit",
    ),
    path(
        "training/march-course/assault-course/",
        views.AssaultCourseListView.as_view(),
        name="assault_course_list",
    ),
    path(
        "training/march-course/assault-course/<int:pk>/edit/",
        views.AssaultCourseUpdateView.as_view(),
        name="assault_course_edit",
    ),
]
