# Generated by Django 6.1 on 2026-08-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_remove_individualcoursename_unique_course_name_per_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Individual Course Level',
                'verbose_name_plural': 'Individual Course Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualCourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='training.individualcourselevel')),
            ],
            options={
                'verbose_name': 'Individual Course Name',
                'verbose_name_plural': 'Individual Course Names',
                'ordering': ['level__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualQual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('spl', models.CharField(blank=True, max_length=255)),
                ('qual_for_next_promotion', models.BooleanField(default=False)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='training.individualcoursename')),
                ('solider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='common.person')),
            ],
            options={
                'verbose_name': 'Individual Qualification',
                'verbose_name_plural': 'Individual Qualifications',
                'ordering': ['-year', 'course_name__level__name', 'course_name__name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationInMajCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gp_trg', models.CharField(max_length=256)),
                ('st', models.CharField(max_length=256)),
                ('wt', models.CharField(max_length=256)),
                ('fi', models.CharField(max_length=256)),
                ('ihwf', models.CharField(max_length=256)),
                ('ff', models.CharField(max_length=256)),
                ('solider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_competitions', to='common.person')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='YearlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cycle', models.CharField(choices=[('1st Cycle', '1st Cycle'), ('2nd Cycle', '2nd Cycle'), ('3rd Cycle', '3rd Cycle'), ('4th Cycle', '4th Cycle')], max_length=20)),
                ('option', models.CharField(choices=[('PLve', 'P/Lve'), ('GP Trg', 'GP Trg'), ('Course', 'Course'), ('Admin', 'Admin')], max_length=20)),
                ('solider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_plans', to='common.person')),
            ],
            options={
                'ordering': ['-year', 'cycle'],
            },
        ),
        migrations.AddConstraint(
            model_name='individualcoursename',
            constraint=models.UniqueConstraint(fields=('level', 'name'), name='unique_course_name_per_level'),
        ),
        migrations.AddConstraint(
            model_name='individualqual',
            constraint=models.UniqueConstraint(fields=('solider', 'course_name', 'year'), name='unique_person_course_year'),
        ),
    ]
