# Generated by Django 6.1 on 2026-08-21 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_individualcoursename_unique_course_name_per_level_and_more'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_days', models.PositiveIntegerField(editable=False, help_text='Number of days in this leave period, including both dates.')),
                ('total_no_days', models.PositiveIntegerField(help_text='Total days of this leave type taken by the soldier.')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('solider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_states', to='common.person')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_states', to='training.leavetype')),
            ],
            options={
                'verbose_name': 'Leave State',
                'verbose_name_plural': 'Leave States',
                'ordering': ['-from_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('to_date__gte', models.F('from_date'))), name='leave_state_valid_dates')],
            },
        ),
    ]
