# Generated by Django 6.1 on 2026-08-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_individualcoursename_unique_course_name_per_level_and_more'),
        ('training', '0002_leavetype_leavestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationInSportsTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_comp', models.CharField(max_length=255, verbose_name='Name of Competition/Training')),
                ('type_of_comp', models.CharField(choices=[('sports', 'Sports'), ('training', 'Training')], max_length=20)),
                ('significant_achievement', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='yearlyplan',
            options={'ordering': ['-year', 'cycle'], 'verbose_name': 'Yearly Plan', 'verbose_name_plural': 'Yearly Plans'},
        ),
        migrations.AddConstraint(
            model_name='yearlyplan',
            constraint=models.UniqueConstraint(fields=('solider', 'year', 'cycle'), name='unique_yearly_plan_cycle'),
        ),
        migrations.AddField(
            model_name='participationinsportstraining',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_trainings', to='common.person'),
        ),
    ]
