# Generated by Django 6.1 on 2026-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_individualcoursename_unique_course_name_per_level_and_more'),
        ('training', '0003_participationinsportstraining_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationinmajcom',
            options={'ordering': ['-year'], 'verbose_name': 'Participation in Major Commitment', 'verbose_name_plural': 'Participation in Major Commitments'},
        ),
        migrations.AlterField(
            model_name='participationinmajcom',
            name='ff',
            field=models.CharField(blank=True, max_length=256, verbose_name='FF'),
        ),
        migrations.AlterField(
            model_name='participationinmajcom',
            name='fi',
            field=models.CharField(blank=True, max_length=256, verbose_name='FI'),
        ),
        migrations.AlterField(
            model_name='participationinmajcom',
            name='gp_trg',
            field=models.CharField(blank=True, max_length=256, verbose_name='GP Trg'),
        ),
        migrations.AlterField(
            model_name='participationinmajcom',
            name='ihwf',
            field=models.CharField(blank=True, max_length=256, verbose_name='IHWF'),
        ),
        migrations.AlterField(
            model_name='participationinmajcom',
            name='st',
            field=models.CharField(blank=True, max_length=256, verbose_name='ST'),
        ),
        migrations.AlterField(
            model_name='participationinmajcom',
            name='wt',
            field=models.CharField(blank=True, max_length=256, verbose_name='WT'),
        ),
        migrations.AddConstraint(
            model_name='participationinmajcom',
            constraint=models.UniqueConstraint(fields=('solider', 'year'), name='unique_majcom_per_soldier_year'),
        ),
    ]
