# Generated by Django 6.1 on 2026-08-23 01:35

import django.db.models.deletion
from django.db import migrations, models


COURSE_LEVELS = [
    "Bde Lvl Cadre",
    "Div Lvl Cadre",
    "Army Lvl Course",
    "Misc Trg",
]
LEAVE_TYPES = [
    "Privilege Leave",
    "Casual Leave",
]


def seed_excel_lookups(apps, schema_editor):
    IndividualCourseLevel = apps.get_model("training", "IndividualCourseLevel")
    LeaveType = apps.get_model("training", "LeaveType")
    for name in COURSE_LEVELS:
        IndividualCourseLevel.objects.get_or_create(name=name)
    for name in LEAVE_TYPES:
        LeaveType.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_drop_person_on_leave_column'),
        ('training', '0010_ret_firing_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualqual',
            name='pe',
            field=models.CharField(blank=True, max_length=255, verbose_name='PE'),
        ),
        migrations.AddField(
            model_name='leavestate',
            name='slot',
            field=models.CharField(blank=True, choices=[('P lve', 'P lve'), ('C lve-1', 'C lve-1'), ('C lve-2', 'C lve-2'), ('C lve-3', 'C lve-3'), ('C lve-4', 'C lve-4'), ('C lve-5', 'C lve-5')], max_length=20, verbose_name='Excel slot'),
        ),
        migrations.AlterField(
            model_name='gpfiring',
            name='attempt',
            field=models.CharField(choices=[('Prac-1', 'Prac-1'), ('Prac-2', 'Prac-2'), ('Prac-3', 'Prac-3'), ('Prac-4', 'Prac-4'), ('Prac-5', 'Prac-5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sosnfiring',
            name='attempt',
            field=models.CharField(choices=[('Prac-1', 'Prac-1'), ('Prac-2', 'Prac-2'), ('Prac-3', 'Prac-3')], max_length=255),
        ),
        migrations.CreateModel(
            name='AssaultCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.CharField(choices=[('Prac-1', 'Prac-1'), ('Prac-2', 'Prac-2'), ('Prac-3', 'Prac-3'), ('Prac-4', 'Prac-4'), ('Prac-5', 'Prac-5')], max_length=255)),
                ('date_of_event', models.DateField()),
                ('time', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=255)),
                ('solider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assault_courses', to='common.person')),
            ],
            options={
                'verbose_name': 'Assault Course',
                'verbose_name_plural': 'Assault Courses',
                'ordering': ['-date_of_event', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='SpeedMarch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.CharField(choices=[('Prac-1', 'Prac-1'), ('Prac-2', 'Prac-2'), ('Prac-3', 'Prac-3'), ('Prac-4', 'Prac-4'), ('Prac-5', 'Prac-5'), ('Prac-6', 'Prac-6')], max_length=255)),
                ('date_of_event', models.DateField()),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=255)),
                ('solider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_marches', to='common.person')),
            ],
            options={
                'verbose_name': 'Speed March',
                'verbose_name_plural': 'Speed Marches',
                'ordering': ['-date_of_event', 'attempt'],
            },
        ),
        migrations.RunPython(seed_excel_lookups, migrations.RunPython.noop),
    ]
