# Generated by Django 6.1 on 2026-08-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_speed_march_assault_qual_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTrainingCyclePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('cycle', models.PositiveSmallIntegerField(choices=[(1, '1st Trg Cycle'), (2, '2nd Trg Cycle'), (3, '3rd Trg Cycle'), (4, '4th Trg Cycle')])),
                ('bde_lvl_cadre', models.TextField(blank=True, verbose_name='Bde Lvl Cadre')),
                ('div_lvl_cadre', models.TextField(blank=True, verbose_name='Div Lvl Cadre')),
                ('pre_course_pe', models.TextField(blank=True, verbose_name='Pre-Course/PE')),
                ('gpt', models.TextField(blank=True, verbose_name='GPT')),
                ('misc_trg_event', models.TextField(blank=True, verbose_name='Misc Trg Event')),
            ],
            options={
                'ordering': ['year', 'cycle'],
                'constraints': [models.UniqueConstraint(fields=('year', 'cycle'), name='unique_unit_training_cycle_per_year')],
            },
        ),
    ]
