# Generated by Django 6.1 on 2026-08-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_person_present_rank_date_and_more'),
        ('training', '0012_unittrainingcycleplan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unittrainingcycleplan',
            name='unique_unit_training_cycle_per_year',
        ),
        migrations.AddField(
            model_name='unittrainingcycleplan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_training_cycle_plans', to='common.organization'),
        ),
        migrations.AddConstraint(
            model_name='unittrainingcycleplan',
            constraint=models.UniqueConstraint(fields=('year', 'cycle', 'organization'), name='unique_unit_training_cycle_per_company_year'),
        ),
    ]
