# Generated by Django 6.1 on 2026-08-26 14:33

import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_remove_unittrainingcycleplan_unique_unit_training_cycle_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationinsportstraining',
            name='cycle',
            field=models.CharField(choices=[('1st Cycle', '1st Cycle'), ('2nd Cycle', '2nd Cycle'), ('3rd Cycle', '3rd Cycle'), ('4th Cycle', '4th Cycle')], default='1st Cycle', max_length=20),
        ),
        migrations.AddField(
            model_name='participationinsportstraining',
            name='year',
            field=models.PositiveIntegerField(default=training.models.current_year),
        ),
    ]
