# Generated by Django 6.1 on 2026-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_qual_year_and_cycle_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavestate',
            name='slot',
            field=models.CharField(blank=True, choices=[('P lve', 'P lve'), ('C lve-1', 'C lve-1'), ('C lve-2', 'C lve-2'), ('C lve-3', 'C lve-3'), ('C lve-4', 'C lve-4'), ('C lve-5', 'C lve-5'), ('J/L', 'J/L'), ('M/L', 'M/L'), ('Course', 'Course'), ('Cadre', 'Cadre'), ('Comd', 'Comd'), ('Att', 'Att'), ('Hosp', 'Hosp'), ('Demob', 'Demob'), ('Fdmn', 'Fdmn'), ('Teknaf', 'Teknaf'), ('OSL', 'OSL')], max_length=20, verbose_name='Excel slot'),
        ),
    ]
