# Generated by Django 6.1 on 2026-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_alter_leavestate_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavestate',
            name='slot',
            field=models.CharField(blank=True, max_length=20, verbose_name='Excel slot'),
        ),
    ]
